travis:
  secure:
    BINSTAR_TOKEN: XDoPjdqGelEEt3D9qelKgwR/NvFHKwWgkhQSBVu4+hh35M0U6QwuOi3ndJQjh0nDuUBK09RZKbJ+yhpu9PVw27iHCXZDG/NHzjjLDe7q1sA70+SI7zisHlRKg2pibqA2tBYy2TKMxFSXFG51L7nx66/dkSIkte7MEinmlX/l2I855g2J70CKmjYSkIX319CCO4pjx9S9IV/wfBR1cYlsZhabUiB6UYrKACORehsV0SIzNCbfg09d6re98zcmUmkab+HjxE2tAtXiEmPhQtvThjZJP/+9XkEayILguF0XJDbAZNy+b8im1j6GxMsXwl1tDs3h8QUCu1UiarXrfkKhkR0lWMHnu0sT2zQhWiXRoglj/wXlVuP90YNZgtxX9zF/0QW6AYQ2+dymK4DB71ZcKIqMcdNrLwoKxQVtl72jWupQUy3JnQFQnymvkFRgl/wXV7FckoHAmKopK1tXnmDOmBwT1bOTpvq3IexWWGF3bj/2hf7riKxNuph/5p7GVws9yCSbm3Khkwc3Mujkcz/DIae3IRL+Yee6Rip23GYMuSUevk5G1/hlfku8m/7pE7jAHbbaGrSfGcXFZYicIYjEkyL/mZnaA5t2oRTkIpSj06d6cEFeynOPV3E5odHnrpq9KYa//rswuGVa+GoU3n3dLMQxHvzpnOOb0V8YxmWDMGE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
